name = "TSviews"
uuid = "799c754c-8754-4cd1-bf0b-1e2c4f3d5111"
authors = ["petedmccallum"]
version = "0.1.0"

[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ECHOsched = "a70fbbd2-9a54-48cc-9e7e-b89de863ed17"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
